server:
    port: 8081
    servlet:
        context-path: /VetClinic

spring:
    datasource:
        url: jdbc:h2:file:./db/h2_demo;DB_CLOSE_ON_EXIT=FALSE;
        driverClassName: org.h2.Driver
        username: sa
        password: password
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true